name: chptr_13
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.7
  json_annotation: ^4.1.0
  chopper: ^4.0.1
  logging: ^1.0.1
  provider: ^6.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.1
  json_serializable: ^4.1.4
  chopper_generator: ^4.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/
